name: CI

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint pytest pytest-cov requests-mock
          pip install -r requirements.txt
      - name: Run Pylint
        run: pylint website/

  test:
    runs-on: ubuntu-latest
    needs: lint 
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov requests-mock
          pip install -r requirements.txt
      - name: Set API Keys
        run: |
            echo "API_KEY=${{ secrets.API_KEY }}" >> $GITHUB_ENV
      - name: Run Tests with Coverage
        run: |
          pytest --cov=website --cov-report=term-missing